### ISSUE TITLE
Cypress commands as Allure steps

### ISSUE THREAD

**Issue by wasder** [mkmozgawa/cypress-allure#2]
It would be cool to see Cypress commands as Allure steps in report. 
Maybe it could be achieved with [Cypress events.](https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events)

**Comment by mkmozgawa** [comment]
Hm, I wonder about the usability of displaying precisely the Cypress commands as steps, but showing the steps of a test to pinpoint exactly where it went wrong would be useful. No idea atm how to approach that, though. I'll look into the events API! Obviously, PRs are welcome :)
